name: Jest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  eslint:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Jest
        run: yarn run test
